travis:
  secure:
    BINSTAR_TOKEN: P+e4OKsfCbWaZVftwYwMyyOwvoqIRaJ3xV5W3enJj2K714PQjHr1Bxu0H9t0CKzcte4XynuUUE8NVJoLYkJyfNKIGiDseP5hZwA1s7elynauw/WOQ5R5Zsf5ySQHVBqGA9u4lxGPK5Lb/9rU4cQmMkysOuY4/VRQQmO4uiOXhDLMd5xNLf2T6c63eyDZUB15pWsBcE1kfeBcqqXfzf0vbFrm3VeZbREq+I2vjcgl76nnkVa/hSmLbTHaPv+OeHwRwkvT4F32m8ST4+XUuzNd16HGUkql+3R7htxbMBZ1k1FEHDjHitI7H/4SrnbenTQFtXTyrQK+c0WmH5zJXW5x7dG/wNID9WClSXXDa0TmSn2SltzyaZh32reQmOtYTbIT8LZB9+2tD5oTZ89lL89CsMJot4wZvsvIsbI+5Ph4qL3rrPORlPv4ZuKR4bC6C5kT3lbDq+xv4pivyCgdehmQDntB2ZPaplswaO0h7DaE2Q0T0g+PYOIKzVeHTpvpdrgJl9wIzEgg9nkQXPWEtdstxdRb6eSfLbmZR4IPn6d10nQzStR0vOIpSxSyT0nyONYSBwXRt/hNEd3IPNiHbsp30+15mnSM/5Kf5UHU1TMCdMjJZTdUv+aE9eOdwaI7kJSkuJwxS4xGB9Hq+BKzAfDjjkEdBIqZ+xHHIr5crz+Bm48=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
