appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: pAk3M9IkiKLvEO6RVHR3uZsWVt8EJy59PNQUoTXdK0BQT1dr6JN5PGveGjgiZZxVmnmKhHUvRPwCdS/W3KTAFo4uvcNxDua4V6Bgg8E44WyBHqsk+GY7H09loHlKfIK2JfbgmI0EfKndRFyNnor4FPeNI+dCTraHaGNmV0Pr67WORxN+gztibCOvA5nUQsa2Dt1QFZvU3ce1bSHAK4Yif9MjbP3ptD+dfXH6XLjwBsQM/SLOGXnFsTU9oeAayoBWUvfMLK8t48LG+7Ij5u/87LSD8xnYApf9zDSCHkeclXjTGdNu7KZsSiKZPvzbCVvVa3SqyZKxY3GJVV8cE5l4dFhvFyMVL4VYzsSl5Xp7dNBw60NOFKcMv763723GB/py+G2FC0b+UyrA0XdbNWwDuUo2AAOmKaPaRa3MlYAmIEmD+Vz35KNnjfrYYKWzLjVIsFz6h/vdYtaYWTuMede4mvN9fqGHGoND5NdHcEqkqNT0PF/n1S2v3qiTa7HuEktj09nmurf6Wdpt3qLSD5olzC+XOUAXasr2jXMBvC6kaHbSfsnEFE4dQAOjscX8YpBqJTpptntATxu1Wx3slGT/gZPxrrbvCgS4a9fS5wICc3AoGaTx7AcR1KJaTNzyRCBxUGNpeKkp8YLoKOrA1anYRB+JaetIn/ygGZhzuaGbBWA=
conda_forge_output_validation: true
